error handling in prepare-for-darwin

diff --git a/guest/prepare-for-darwin b/guest/prepare-for-darwin
--- a/guest/prepare-for-darwin
+++ b/guest/prepare-for-darwin
@@ -28,6 +28,7 @@ do
 	echo $file
 	curl -O http://www.gura-lang.org/guest/$file
 done
+failed=""
 #---------------------------------------------------------------------------
 function setup_dylib() {
 	local srcdir=$1
@@ -49,7 +50,7 @@ function setup_dylib() {
 tar xfz SDL2-2.0.4.tar.gz
 pushd SDL2-2.0.4
 ./configure
-make $make_option
+make $make_option || failed="$failed SDL2"
 popd
 rm -f include/SDL2
 ln -sf ../SDL2-2.0.4/include/ include/SDL2
@@ -58,7 +59,7 @@ setup_dylib SDL2-2.0.4/build/.libs dylib
 tar xfz expat-2.1.0.tar.gz
 pushd expat-2.1.0
 ./configure
-make $make_option
+make $make_option || failed="$failed expat"
 popd
 rm -f include/expat
 ln -sf ../expat-2.1.0/lib/ include/expat
@@ -67,7 +68,7 @@ ln -sf ../expat-2.1.0/.libs/libexpat.a lib/libexpat.a
 tar xfy freetype-2.5.3.tar.bz2
 pushd freetype-2.5.3
 ./configure
-make $make_option
+make $make_option || failed="$failed freetype"
 popd
 rm -f include/freetype
 ln -sf ../freetype-2.5.3/include/ include/freetype
@@ -77,7 +78,7 @@ ln -sf ../freetype-2.5.3/objs/.libs/libfreetype.a lib/libfreetype.a
 tar xfy fontconfig-2.11.1.tar.bz2
 pushd fontconfig-2.11.1
 ./configure PKG_CONFIG=../pkg-config-fake FREETYPE_CFLAGS=-I../../include/freetype FREETYPE_LIBS="-L../../lib -lfreetype -lz -lbz2" EXPAT_CFLAGS=-I../../include/expat EXPAT_LIBS="-L../../lib -lexpat"
-make $make_option
+make $make_option || failed="$failed fontconfig"
 popd
 rm -f include/fontconfig
 ln -sf ../fontconfig-2.11.1/ include/fontconfig
@@ -86,7 +87,7 @@ setup_dylib fontconfig-2.11.1/src/.libs dylib
 tar xfy gmp-6.0.0a.tar.bz2
 pushd gmp-6.0.0
 ./configure
-make $make_option
+make $make_option || failed="$failed gmp"
 popd
 rm -f include/gmp
 ln -sf ../gmp-6.0.0/ include/gmp
@@ -95,7 +96,7 @@ setup_dylib gmp-6.0.0/.libs dylib
 tar xfz jpegsrc.v9a.tar.gz
 pushd jpeg-9a
 ./configure
-make $make_option
+make $make_option || failed="$failed jpegsrc"
 popd
 rm -f include/jpeg
 ln -sf ../jpeg-9a/ include/jpeg
@@ -104,7 +105,7 @@ ln -sf ../jpeg-9a/.libs/libjpeg.a lib/libjpeg.a
 tar xfz libpng-1.6.12.tar.gz
 pushd libpng-1.6.12
 ./configure
-make $make_option
+make $make_option || failed="$failed libpng"
 popd
 rm -f include/png
 ln -sf ../libpng-1.6.12/ include/png
@@ -113,13 +114,13 @@ ln -sf ../libpng-1.6.12/.libs/libpng16.a lib/libpng16.a
 #tar xfz libspectre-0.2.7.tar.gz
 #pushd libspectre-0.2.7
 #./configure 
-#make $make_option
+#make $make_option || failed="$failed libspectre"
 #popd
 #---------------------------------------------------------------------------
 tar xfz onig-5.9.5.tar.gz
 pushd onig-5.9.5
 ./configure
-make $make_option
+make $make_option || failed="$failed onig"
 popd
 rm -f include/onig
 ln -sf ../onig-5.9.5/ include/onig
@@ -128,7 +129,7 @@ ln -sf ../onig-5.9.5/.libs/libonig.a lib/libonig.a
 tar xfz pixman-0.32.6.tar.gz
 pushd pixman-0.32.6
 ./configure
-make $make_option
+make $make_option || failed="$failed pixman"
 popd
 rm -f include/pixman
 ln -sf ../pixman-0.32.6/pixman/ include/pixman
@@ -137,7 +138,7 @@ ln -sf ../pixman-0.32.6/pixman/.libs/libpixman-1.a lib/libpixman-1.a
 tar xfz tiff-3.8.2.tar.gz
 pushd tiff-3.8.2
 ./configure
-make $make_option
+make $make_option || failed="$failed tiff"
 popd
 rm -f include/tiff
 ln -sf ../tiff-3.8.2/libtiff/ include/tiff
@@ -146,7 +147,7 @@ ln -sf ../tiff-3.8.2/libtiff/.libs/libtiff.a lib/libtiff.a
 tar xfy wxWidgets-3.1.0.tar.bz2
 pushd wxWidgets-3.1.0
 ./configure --with-macosx-version-min=10.9 --disable-shared
-make $make_option
+make $make_option || failed="$failed wxWidgets"
 popd
 rm -f include/wx
 rm -f lib/wx
@@ -156,7 +157,7 @@ ln -sf ../wxWidgets-3.1.0/lib/ lib/wx
 tar xfz yaml-0.1.5.tar.gz
 pushd yaml-0.1.5
 ./configure
-make $make_option
+make $make_option || failed="$failed yaml"
 popd
 rm -f include/yaml
 ln -sf ../yaml-0.1.5/include/ include/yaml
@@ -166,7 +167,7 @@ ln -sf ../yaml-0.1.5/src/.libs/libyaml.a lib/libyaml.a
 tar xfJ cairo-1.12.18.tar.xz
 pushd cairo-1.12.18
 ./configure pixman_CFLAGS=-I`pwd`/../include/pixman pixman_LIBS="-L`pwd`/../lib -lpixman-1" PKG_CONFIG=../pkg-config-fake png_CFLAGS=-I`pwd`/../include/png png_LIBS="-L`pwd`/../lib -lpng16" FONTCONFIG_CFLAGS=-I`pwd`/../include/fontconfig FONTCONFIG_LDFLAGS="-L`pwd`/../dylib -lfontconfig" FREETYPE_CFLAGS=-I`pwd`/../include/freetype FREETYPE_LIBS="-L`pwd`/../lib -lfreetype -lbz2" --disable-xlib --disable-xcb --disable-gobject --disable-fc --disable-ps
-make $make_option
+make $make_option || failed="$failed cairo"
 popd
 rm -f include/cairo
 ln -sf ../cairo-1.12.18/src/ include/cairo
@@ -177,5 +178,11 @@ pushd llvm-3.6.1.src
 mkdir build
 cd build
 cmake ..
-make $make_option
+make $make_option || failed="$failed llvm"
 popd
+#---------------------------------------------------------------------------
+if [ "$failed" != "" ] ; then
+   echo ======================================================================
+   echo Error occured:$failed
+   echo ======================================================================
+fi
